### ISSUE TITLE
Run actions without update authorization

### ISSUE THREAD

**Issue by GuidoHendriks** [laravel/nova-issues#114]
It's currently only possible to run actions if you're authorized to update it, as it filters it by `authorizedToUpdate($request)`. That's a problem for me, as I don't want to the update feature on a resource, but just the ability to run an action on it.

It would be great if there was a way to run actions without having to enable updating.

(Nova v1.0.5)

**Comment by poxin13** [comment]
Just ran into this too. Even adding the canRun method and defining my own policy, it still requires update.

**Comment by Andy-Baker** [comment]
Yep hit this yesterday with v1.0.6.

I can foresee similar problems with lenses, cards etc where different policies might be needed. More granular permissions might be needed, but actions are the most important.

**Comment by shalawani** [comment]
@GuidoHendriks I fall in this trouble too, could you tell me if you solve this issue please

**Comment by GuidoHendriks** [comment]
@shalawani I haven't solve it. Decided to allow editing as well. Not a problem for me at this stage.

**Comment by shalawani** [comment]
@GuidoHendriks I solved it like this.

public function update(User $user, Permission $permission)
    {
        // This condition because Nova authorize update policy method when run the action
        if (!request()->has('name')) {
            return true;
        }

        return false;
    }

**Comment by poxin13** [comment]
Fixed in latest version
`If a canRun callback is defined on an action, it now takes precedence over the update policy method.`

**Comment by davidhemphill** [comment]
This has been fixed in the latest release.

**Comment by chescos** [comment]
Still having this issue with destructive actions

**Comment by scottybo** [comment]
Guess they need `canDelete` and `canForceDelete` options as well as `canSee` and `canRun`

**Comment by chrisvickers** [comment]
This is still a problem. You need delete and force delete (if using soft deletes) to execute a action. I would think that the ->canSee and ->canRun method would supersede these policies?

**Comment by Abdukhaligov** [comment]
In my policies, I had to write this code, after this the actions will work fine

``` 
public function update(User $user, Revision $revision) {
    // This condition because Nova authorize update policy method when run the action
    if (request()->has('action')) {
      return true;
    }

    return false;
  }
```

*have no idea why Nova needs a PUT request before doing any action

**Comment by farshidrezaei** [comment]
> Fixed in latest version `If a canRun callback is defined on an action, it now takes precedence over the update policy method.`

You saved my day .
