### ISSUE TITLE
Unable to Create a Nova Resource that uses a relationship name of “resource”

### ISSUE THREAD

**Issue by JeffBeltran** [laravel/nova-issues#1424]
- Laravel Version: 5.8.3
- Nova Version: 2.0.0
- PHP Version: 7.3.3
- Operating System and Version: macOS.10.14.3
- Browser type and version: chrome.72.0.3626.121

### Description:

No error message but I see a 404 in network tab when I try to create a resource (no other info included in message)

### Steps To Reproduce:

See this Repo to reproduce error [GitHub - JeffBeltran/novaDebug](https://github.com/JeffBeltran/novaDebug)

When I create a “position” and the relationship is set to 

```php
BelongsTo::make(‘Resource’, ‘resource’, ‘App\Nova\ResourceAlias’)
```

I get the above error. However, if I add a new method on the model

```php
public function resourceAlias()
{
  return $this->belongsTo(Resource::class, ‘resource_id’);
}
```

And update the nova resource to 

```php
BelongsTo::make(‘Resource’, ‘resourceAlias’, ‘App\Nova\ResourceAlias’)
```

It works without an issue.  It’s not really a big deal but I just didn’t like that I had to modify my model to make Nova work with my domain. 

As an aside, this is an amazing tool, thanks for making it.

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by JeffBeltran** [comment]
@dkulyk I think i'm running into an edge case here... The recent patch 2.0.1 fixed the issue on the example repo. But when i applied the patch to the actual project i discovered this issue on, i'm still getting the same behavior as above and have to resort to using the aliased relationship again.

I can't seem to duplicate it on the test project now... the only thing I was only able to tell that it appears to be related to this function in nova.php. Any ideas what could be causing this on my end?

```
    public static function resourceForKey($key)
    {
        return collect(static::$resources)->first(function ($value) use ($key) {
            return $value::uriKey() === $key;
        });
    }
```
