### ISSUE TITLE
Metric does not display selected range

### ISSUE THREAD

**Issue by aaronahearne** [laravel/nova-issues#1466]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.1.3
- Operating System and Version: Windows 10 Pro hosting Homestead 8.2 (Vagrant 2.2.3, Virtualbox 7.1.0)
- Browser type and version: Google Chrome 72.0.3626.121

### Description:
A simple trend metric card does not display the selected range. It is always blank.

I believe this to be an issue with the parent (TrendMetric) Vue's 'selectedRangeKey' which is being passed as a prop to the child (SelectControl). The value is being passed as a string, but requires an integer to work correctly.

Note: Using the YTD and MTD custom keys for value ranges returns an error:

    "message": "A non-numeric value encountered",
    "exception": "ErrorException",
    "file": "/home/vagrant/code/cloud/vendor/laravel/nova/src/Metrics/Trend.php",
    "line": 530,

Which may also be related.

**Before**
<img width="1900" alt="before" src="https://user-images.githubusercontent.com/5104743/54745165-ce646200-4bc0-11e9-8a71-480af626efe0.PNG">

**After**
<img width="1920" alt="after" src="https://user-images.githubusercontent.com/5104743/54745164-ce646200-4bc0-11e9-8399-17fc21390bf9.PNG">

### Steps To Reproduce:
Create a standard metric card and register it in a detail view of a resource.

Once the problem has been reproduced, inspect the metric card with the Vue debug bar and change the TrendMetric's selectedRangeKey from a string to an integer (sometimes requires 2 changes to register the change). You will see that the range is then correctly displayed.

Switching the range using the selector resets the selected range key to a string, which then causes the select to become blank again.

```
namespace Cloud\NovaAccounts\Metrics;

use Cloud\Inventory\SalesOut;
use Illuminate\Http\Request;
use Laravel\Nova\Metrics\Trend;

class SalesPerMonth extends Trend
{
    /**
     * Calculate the value of the metric.
     *
     * @param  \Illuminate\Http\Request $request
     * @return mixed
     */
    public function calculate(Request $request)
    {
        return $this->countByMonths(
            $request,
            SalesOut::where('account_id', $request->resourceId),
            'date'
        )
            ->showLatestValue();
    }

    /**
     * Get the ranges available for the metric.
     *
     * @return array
     */
    public function ranges()
    {
        return [
            3 => '3 Months',
            6 => '6 Months',
            12 => '12 Months',
        ];
    }

    /**
     * Determine for how many minutes the metric should be cached.
     *
     * @return  \DateTimeInterface|\DateInterval|float|int
     */
    public function cacheFor()
    {
        // return now()->addMinutes(5);
    }

    /**
     * Get the URI key for the metric.
     *
     * @return string
     */
    public function uriKey()
    {
        return 'sales-per-month';
    }
}
```

**Comment by yovchev** [comment]
You may not be able to replicate this issue unless you compile nova assets from the latest `v2.0.0`  or `v1.3.2` manually (the only reason we had to compile this was to enable vue debugger)

After some digging, I found that in `v1.3.2` some changes were made to 

`nova/resources/js/components/Metrics/Base/TrendMetric.vue (line 6 to 19)`

this 
```html
<div class="flex mb-4">
    <h3 class="mr-3 text-base text-80 font-bold">{{ title }}</h3>

    <select
        v-if="ranges.length > 0"
        @change="handleChange"
        class="ml-auto min-w-24 h-6 text-xs no-appearance bg-40"
    >
        <option
            v-for="option in ranges"
            :key="option.value"
            :value="option.value"
            :selected="option.value == selectedRangeKey"
        >
            {{ option.label }}
        </option>
    </select>
</div>
```
was replaced by this

```html
<div class="flex mb-4">
    <h3 class="mr-3 text-base text-80 font-bold">{{ title }}</h3>

    <select-control
        v-if="ranges.length > 0"
        @change="handleChange"
        class="ml-auto min-w-24 h-6 text-xs no-appearance bg-40"
        :options="ranges"
        :selected="selectedRangeKey"
    />
</div>
```
By getting this changes reverted to the one from `v1.3.1` and compiling the assets this issue is resolved it may have something to do with the way the 
```javascript 
Vue.component('select-control', SelectControl)
```
handles the `selectedRangeKey` probably by adding watcher on the `selected` may fix this.

`nova/resources/js/components/Controls/SelectControl.vue (line 50 to 57)`

```javascript
methods: {
    labelFor(option) {
        return this.label instanceof Function ? this.label(option) : option[this.label]
    },

    attrsFor(option) {
        return _.assign(
            {},
            option.attrs || {},
            { value: option.value },
            this.selected !== void 0 ? { selected: this.selected == option.value } : {}
        )
    },
},
```

Probably will be good idea to let us know what version of the assets is compiled in `nova/public` for every version of nova this way we can look for discrepancies when we run `npm run development` if something is not working.

**Comment by rikless** [comment]
@yovchev Had the same issue on 2.0.1, and never compiled nova assets

**Comment by dkulyk** [comment]
May you simple app with this issue? I cannot reproduce it.

**Comment by Kirich11** [comment]
I've encountered this issue, and found that the selected key is passed, but not the value which is used by the select-control. This is the cause of the problem.
I've modified the Base/ValueMetric and others to pass the :value prop to select-control.
```
<select-control
                v-if="ranges.length > 0"
                @change="handleChange"
                class="ml-auto min-w-24 h-6 text-xs no-appearance bg-40"
                :options="ranges"
                :selected="selectedRangeKey"
                :value="selectedRangeKey" //Here
            />
```
I don't know why it's doesn't affect everyone though

**Comment by foxted** [comment]
This is still happening with the latest version of Nova. @Kirich11 solution is working perfectly though 👍

**Comment by davidhemphill** [comment]
I think we fixed this bug quite a while ago by reverting to the original Nova select code. They also seem to be working on the latest release. Please open a new issue with a way to reproduce the issue if it still persists.
