### ISSUE TITLE
Images/Avatar not displaying in detail view

### ISSUE THREAD

**Issue by ryryan** [laravel/nova-issues#150]
I am using DigitalOcean Spaces to host user profile photos. `Avatar::make('Profile Photo')->disk('spaces')` displays the images fine in the resource index. However they do not appear on the detail view - "This image could not be found" is displayed and the link works fine. Uploading images is fine.
![screen shot 2018-08-24 at 18 01 17](https://user-images.githubusercontent.com/521678/44597513-cded1f80-a7c7-11e8-98f7-e49917a78c8e.png)

**Comment by ryryan** [comment]
This was due to cross-origin resource sharing not being enabled on the DO Space. Odd that it worked on the index though.

**Comment by NSpehler** [comment]
I'm facing the same issue with DigitalOcean Spaces.

I've changed the CORS settings in DigitalOcean, but it doesn't always solve the issue, very odd. Can you share your settings to finally make it work?

I'm surprised it works every time on the index as well...

**Comment by ryryan** [comment]
That's strange @NSpehler. For the time being I'm having to manually make each image (uploaded through Nova) to public permissions on the DO space, as the default is private (need to find a way around that). Other than adding the space details in `filesystems.php` and using `Avatar::make`, there's nothing else to it. CORS was set to domain and GET was the only allowed method.

**Comment by NSpehler** [comment]
Yes, I opened an issue yesterday for the file visibility issue you mentioned: https://github.com/laravel/nova-issues/issues/87#issue-353588629

Here's my temporary workaround solving the file visibility issue. This is dirty fix, but it works in the meantime:

<img width="568" alt="screenshot 2018-08-24 20 07 34" src="https://user-images.githubusercontent.com/379186/44600382-6a6bed80-a7d9-11e8-9c2f-d560e5db200d.png">

Going back to the original issue, can you confirm you have the same settings in DigitalOcean Spaces?

<img width="648" alt="screenshot 2018-08-24 20 09 37" src="https://user-images.githubusercontent.com/379186/44600479-b028b600-a7d9-11e8-8fb9-3ec52df65403.png">

**Comment by ryryan** [comment]
Thank you for that @NSpehler, I will give it a go. Re: CORS I didn’t add any allowed headers - left it blank, and it worked. Fingers crossed it works for you.

**Comment by bonzai** [comment]
`ImageLoader` (component used to display images) is using AJAX to load image from the remote server. That's why there are problems with CORS headers. This could be easily fixed by using [image.onload](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/image.onload).

**Comment by NSpehler** [comment]
Thanks for your feedback @bonzai. Let's hope they can switch to this method instead. 🤞

**Comment by nickels** [comment]
So the following (as per documentation) works fine for me to upload publically.

```
            Avatar::make('Avatar')
                ->disk('spaces')
                ->store(function (Request $request, $model) {
                    return [
                        'avatar' => $request->avatar->storePublicly(config('app.env') . '/avatars', ['disk' => 'spaces'])
                    ];
                })
                ->prunable(),
```

Now what I haven't solved is to actually display the avatar when displaying the resource. So I guess I'll have to use the below from the documentation. And see that work. For now the axios call for the resource is returning 403?

```
    ->preview(function () {
        return $this->value
                    ? Storage::disk($this->disk)->url($this->value)
                    : null;
    })
```

**Comment by nickels** [comment]
So this solution worked for me (as partially mentioned above).

```
            Avatar::make('Avatar')
                ->disk('spaces')
                ->store(function (Request $request, $model) {
                    return [
                        'avatar' => $request->avatar->storePublicly(config('app.env') . '/avatars', ['disk' => 'spaces'])
                    ];
                })
                ->prunable(),
```

This should solve the issue with response 403. It just doesn't append the headers to existing images. As soon as you upload a new image the headers will be appended.

![image](https://user-images.githubusercontent.com/9688615/44983407-59f60880-af79-11e8-8466-e8b58634ee6d.png)

**Comment by danmatthews** [comment]
Having the same issue with S3, has anyone got a CORS configuration working there?

**Comment by danmatthews** [comment]
So after a LONG night with this last night - i got to bed at 4.15am, it turned out that my CORS configuration was working fine, it was browser caching that was (and is) still causing problems.

If i click into a detail view, i still get the "Image not found" message, then when i hard-reload, I get the image.

This is obviously a bit of a shitter for my clients.

![hardrefresh](https://user-images.githubusercontent.com/149426/45034614-e541cd80-b04f-11e8-8127-8b775323b859.gif)

**Comment by playwellsteve** [comment]
I am having the same issue with an S3 public bucket. Originally, the image thumbnails would show on the index page, but not on the detail page. I tried adding a CORSs configuration to the bucket:

`\<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>GET</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>Authorization</AllowedHeader>
	</CORSRule>
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>PUT</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>Content-Type</AllowedHeader>
		<AllowedHeader>x-amz-acl</AllowedHeader>
		<AllowedHeader>origin</AllowedHeader>
	</CORSRule>
</CORSConfiguration>
`
This works to show the image on the detail page, but when I try to edit the resource, I get a 403 forbidden. I removed the CORS configuration, because this removes functionality. Any ideas?

**Comment by bonzai** [comment]
Until this issue get's resolved, you can fix it by yourself - just overwrite the `mounted` method of `resources/js/components/ImageLoader.vue` file:

```js
mounted() {
    Minimum(
        new Promise((resolve, reject) => {
            let image = new Image()
            image.addEventListener('load', () => resolve(image))
            image.addEventListener('error', () => reject())
            image.src = this.src
        })
    )
        .then(image => {
            image.className = 'block w-full'
            image.draggable = false
            this.$refs.card.$el.appendChild(image)
            this.loading = false
        })
        .catch(() => {
            this.missing = true
            this.$emit('missing', true)
            this.loading = false
        })
},
```

**Comment by playwellsteve** [comment]
I haven't made the change to the vue component, but after the last nova update (1.12) and the above CORS configuration, I now get the 403 when editing some, but not all images on S3.

**Comment by danmatthews** [comment]
Changed the Vue component myself but it hasn't affected it - i'm guessing you'll need to recompile the JS for Nova after doing that.

This is currently stopping me being able to deploy an admin panel for a client which sucks - @bonzai do you have any steps on how to recompile Nova's JS completely?

**Comment by bonzai** [comment]
@danmatthews: Execute the following commands inside your "nova" directory:

```console
$ cp webpack.mix.js.dist webpack.mix.js
$ yarn
$ yarn prod
```

Don't forget to publish new assets:

```console
$ php artisan nova:publish
```

**Comment by joselara** [comment]
Same problem with S3.

**Comment by HeshamEG** [comment]
if you are running localy
you can modify config/filesystems.php in 'public section to be like this  ' ` 'public' => [
            'driver' => 'local',
            'root' => storage_path(''),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],`
then you have to enable cors you can use <a href="https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en">cors extention </a>

**Comment by bonzai** [comment]
YO @davidhemphill, could you look at this issue?

The `ImageLoader` component should work without changing any settings (like CORS). If I apply fix from my previous comment - https://github.com/laravel/nova-issues/issues/150#issuecomment-419217516 - it works without any problem.

**Comment by davidhemphill** [comment]
@bonzai This has been fixed (using your fix) and will be included in an upcoming release.
