### ISSUE TITLE
TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1735]
- Nova Version: 2.0.9

### Description:

On Nova 2.0.7 all ok!

1) Custom field don't rendered on form.

2) Error on press create button on create resource form.
``` 
vendor.js?id=eaffe66c3a2800ae7df2:1

TypeError: Cannot read property 'status' of undefined
    at p.<anonymous> (app.js?id=af7f60e144c36d0eb627:1)
    at y (app.js?id=af7f60e144c36d0eb627:1)
    at Generator._invoke (app.js?id=af7f60e144c36d0eb627:1)
    at Generator.e.<computed> [as next] (app.js?id=af7f60e144c36d0eb627:1)
    at o (app.js?id=af7f60e144c36d0eb627:1)
    at app.js?id=af7f60e144c36d0eb627:1
    at new Promise (<anonymous>)
    at new t (app.js?id=af7f60e144c36d0eb627:1)
    at p.<anonymous> (app.js?id=af7f60e144c36d0eb627:1)
    at p.<anonymous> (app.js?id=af7f60e144c36d0eb627:1)
It @ vendor.js?id=eaffe66c3a2800ae7df2:1
jt @ vendor.js?id=eaffe66c3a2800ae7df2:1
Yt @ vendor.js?id=eaffe66c3a2800ae7df2:1
(anonymous) @ vendor.js?id=eaffe66c3a2800ae7df2:1
Promise.catch (async)
Pt @ vendor.js?id=eaffe66c3a2800ae7df2:1
n @ vendor.js?id=eaffe66c3a2800ae7df2:1
Zo.i._wrapper @ vendor.js?id=eaffe66c3a2800ae7df2:1
```

### Steps To Reproduce:

Add to fields

```php
            NestedForm::make(__('Files'), 'files', File::class)
                ->min(1)
                ->max(1)
                ->open(true)
                ->rules('required', 'min:1')->hideWhenUpdating(),
```

https://github.com/yassipad/laravel-nova-nested-form

**Comment by davidhemphill** [comment]
Please read the docs next time you update. This has already been addressed many times. You need to make sure Nova's CSS and JS assets are up-to-date as well per the docs: https://nova.laravel.com/docs/2.0/installation.html#updating-nova-s-assets

**Comment by 4n70w4** [comment]
@davidhemphill Why did you decide that I did not do this?
You have broken backward compatibility, it needs to be solved, but not to close the issue.

I make:
```
php artisan nova:publish
php artisan view:clear
```

And clear cache + hard reload in chrome.

Result: the same error.

**Comment by flxsource** [comment]
@4n70w4 I discovered [this](https://github.com/whitecube/nova-flexible-content/issues/27#issuecomment-498069912) issue when using `whitecube/nova-flexible-content`, relating to creation of a `FormData` object.

In my case, it's `tanmuhittin/nova-scroll-top`, which uses [xhook](https://github.com/jpillora/xhook), which proxies the FormData object (amongst other things). They say:

> can do this safely because all XHR is hooked, so we can ensure the real FormData object is used on send.

This appears not to be the case here, as another package (in my case, `whitecube/nova-flexible-content` is using `FormData` directly, NOT via `XHR`.

I'll open a ticket on the xhook repo, but a temporary work around is detailed on the issue linked in the nova-flexible-content repo.

**Comment by mavericksthinker** [comment]
Hope it will help others to fix the issue due to the new feature. Currently implemented with v 2.0.11 of nova
```
 public function jsonSerialize()
    {
        return array_merge([
            **'panel' => $this->panel,**
            'component' => $this->component,
            'prefixComponent' => true,
            'resourceName' => $this->resourceName,
```
and avoid keeping the HasMany and BelongsTo fields as readonly()

**Comment by jason-rudland** [comment]
I'm struggling to understand how to fix this - can anyone help?

I'm getting "TypeError: Cannot read property 'fields' of undefined " in the browser console after I did a composer update. It is connected to me using the nova-tabs package.

I did the following, and used --force after it didn't work

> php artisan nova:publish
> php artisan view:clear

If I rollback the composer update to a previous version it all starts working again, but leaving it at an old version causes difficulty when creating new resource-tools.

**Comment by Skullbock** [comment]
@jason-rudland in my case was the Sortable field (another nova 3rd party package)
In my case, i fixed it by displaying it only on index.

In general, try to find any nova field that doesn't show up in the form for your resource and applying a ->onlyOnIndex() or similar call to avoid showing it into the form

**Comment by JeasonZuo** [comment]
> I'm struggling to understand how to fix this - can anyone help?
> 
> I'm getting "TypeError: Cannot read property 'fields' of undefined " in the browser console after I did a composer update. It is connected to me using the nova-tabs package.
> 
> I did the following, and used --force after it didn't work
> 
> > php artisan nova:publish
> > php artisan view:clear
> 
> If I rollback the composer update to a previous version it all starts working again, but leaving it at an old version causes difficulty when creating new resource-tools.

I think you question is caused by upgrade of laravel-mix. 
[https://laravel-mix.com/docs/4.0/upgrade](url)
You can add `.default` in your field.js file like this
`Nova.booting((Vue, router, store) => {
    Vue.component('index-map-position', require('./components/IndexField').default)
    Vue.component('detail-map-position', require('./components/DetailField').default)
    Vue.component('form-map-position', require('./components/FormField').default)
})
`

**Comment by JeasonZuo** [comment]
I think your problem is caused by the laravel-mix upgrade.
https://laravel-mix.com/docs/4.0/upgrade
You can add .default to the field.js file.
Nova.booting((Vue, router, store) => { Vue.component('index-map-position', require('./components/IndexField').default) Vue.component('detail-map-position', require('./components/DetailField').default) Vue.component('form-map-position', require('./components/FormField').default) })

**Comment by binaryk** [comment]
@davidhemphill did you consider to revert the previous avatar? This one is too serious that's why people dislike the answer above :D

**Comment by admench** [comment]
Still getting this issue here with a custom field. Commenting out the custom field (which is set to only show on create form) fixes this.

I have republished nova assets and cleared views.
For fullness, I ran `optimize:clear`

Any other tips people? Many thanks in advance.
Laravel v5.8.38
Nova v2.12.0

**Comment by kiakahaDZ** [comment]
Hello there have you found any solution for this problem I am facing this prob i have follow any kind of proposal on internet but i haven't solve it.
PS: in the local it work fine but on server in product it show me this problem in the console
