### ISSUE TITLE
BelongsToMany Show specific pivot fields in index

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#186]
I've got a Suppliers resource that has a list of products with a price (pivot). It make sense to me to display the price in the index list.

```php
BelongsToMany::make('Products')
            ->fields(function () {
                return [
                    Text::make('Precio', 'price'),
                ];
            }),
```

This is only visible when I edit it, not even in the display view

**Comment by AdamHutchison** [comment]
I’m having a similar issue. The pivot data updates / creates correctly but then does not show on the index despite the index headings being present.

**Comment by disitec** [comment]
also referenced here #40

**Comment by zeroseed** [comment]
+1
i thought this is just me , 
Checking console and view json response and no such field returned from BelongsToMany relation

**Comment by dastiii** [comment]
I've noticed the same using a **MorphToMany** field. 
On the edit or create pages everything works fine whereas the index does only show the table headers but not the actual values.

**Comment by BengtHagemeister** [comment]
+1

**Comment by bayareawebpro** [comment]
Temporary Fix:

```
/**
     * Get the pivot fields for the relationship.
     * @return array
     */
    public function __invoke()
    {
        return [
            Text::make('Notes', 'notes')
                ->rules('nullable','string','max:1000')
                ->displayUsing(function(){
                    return isset($this->pivot) ? $this->pivot->notes : '-';
                }),
        ];
    }
```

**Comment by drehimself** [comment]
Same issue for me, only shows on the edit screen but headings show on index page. Taylor seems to have it working on the index page in his Laracon demo: https://www.youtube.com/watch?v=pLcM3mpZSV0&t=2400s

![pivot_table_empty_fields](https://user-images.githubusercontent.com/4316355/44640693-258ab700-a991-11e8-8b62-cc1de99af9bb.png)

**Comment by exwizzard** [comment]
I had the same issue and it started working when I made the same field on both nova resources.

**Comment by Livijn** [comment]
Using `MorphToMany` it seems as if it doesn't even add the title to the index. It is visible at edit and create page though. On [this part of the docs](https://nova.laravel.com/docs/1.0/resources/relationships.html#pivot-fields-2), it says

> Once these fields are attached to the relationship field, they will be displayed on the related resource index.

This definitely appears to be a bug.

**Comment by michaelradionov** [comment]
+1

**Comment by ardyn** [comment]
I'm not even seeing the column header in the index view of attached models on the resource detail screen. When attaching or editing the attachments, i see the pivot data.
```
// In Nova\Invoice
BelongsToMany::make('Installers', 'installers', \App\Nova\User::class)->fields(function() {
  return [
    Text::make('Contribution', 'contribution'),
  ];
})
```
Installers are Users. 'installers' is the method name of the belongsToMany relationship in User model.
I do not have a belongsToMany field set in Nova\User nor a invoices method in App\User.

**Comment by czemu** [comment]
@disitec I had the same problem (empty field was visible in the edit form and the value doesn't show up in the relation index).

In your model, you have to add `->withPivot('field_name')` to your relationship definition and it will be working file.

**Comment by loren138** [comment]
If you happen to have fields with the same name in the pivot table and the parent table the fix by @czemu still won't get them to come through.
I modified `src/Fields/Field.php` in `resolveForDisplay` to pass the full resource as the second parameter int the displayCallback.
```
        if (is_callable($this->displayCallback) &&
            data_get($resource, $attribute, '___missing') !== '___missing') {
            // MODIFICATION MODIFIED
            $this->value = call_user_func(
                $this->displayCallback, data_get($resource, $attribute), $resource
            );
        }
```

Then you can do: (where `User1` is the name of the column)
```
->displayUsing(function ($field, $resource) {
                return $resource->pivot->User1;
            }),
```

**Comment by NeroAzure** [comment]
I think i have experienced the same issue, in my case i have seen that the fields visible in the detail view had to have a pivot.-prefix and that prefix did break the fields in the attach-view, since it happens in the context of the pivot they mustn't have the prefix, my workaround were to implement the filds twice, one for index with prefix and one for the attach/edit view without prefix

**Comment by taylorotwell** [comment]
Fixed in upcoming release.

**Comment by pr-baernholdt** [comment]
I have the same issue in v1.1.4
It doesn't show the column on the pivot table of MorphToMany relation.
Tried both solutions, no luck! I see no column in the index page of the model called in the detail view of the calling model.
`App\Nova\Band`:
```
            MorphToMany::make('Reviews', 'reviews', User::class)
                ->searchable()
                ->fields(function () {
                    return [
                        Text::make('Review comment', 'review_comment')
                            ->displayUsing(function(){
                                return isset($this->pivot) ? $this->pivot->review_comment : '-';
                            }),
                        Text::make('Rating', 'review_rating'),
                    ];
                }),
```
`App\Models\User`:
```
    /**
     * Band reviews
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function bandReviews()
    {
        return $this->morphedByMany(
            Band::class,
            'review_object',
            'reviews',
            'user_id',
            'review_object_id',
            'user_id',
            'band_id'
        )->withPivot([
            'review_rating',
            'review_comment'
        ]);
    }
```
`App\Models\Band`:
```
    /**
     * Reviews
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function reviews()
    {
        return $this->morphToMany(
            User::class,
            'review_object',
            'reviews',
            'review_object_id',
            'user_id',
            'band_id',
            'user_id'
        )->withPivot([
            'review_comment',
            'review_rating',
        ]);
    }

**Comment by iwasingh** [comment]
Is it fixed? Doesn't seems for me

**Comment by flexchar** [comment]
A possible bug when using MorphToMany relationship and [_Customizing The pivot Attribute Name_](https://laravel.com/docs/5.7/eloquent-relationships#defining-relationships) option.

If relationship pivot table name is changed using `as` method, 
![image](https://user-images.githubusercontent.com/9198896/48753760-8563d600-ecd2-11e8-89e7-10c29ca77422.png)
then Nova will not display value on index/view pages. However, Nova does update pivot entry correctly.

**Comment by larsjanssen6** [comment]
@taylorotwell it's not fixed. Same problem here. When you edit the pivot value it's visible but on the index page it's not.

**Comment by dmitryvasilevskiy** [comment]
Is it fixed? Doesn't seems for me

**Comment by dmitryvasilevskiy** [comment]
With this code i only see field onForms.
```
MorphToMany::make('CustomFields','CustomFields', 'App\Nova\CustomField')->fields(function () {
                return [
                    Text::make('Value', 'value')
                        ->displayUsing(function(){
                            return isset($this->pivot) ? $this->pivot->value : '-';
                        }),
                ];
            }),
```

**Comment by techn0guy** [comment]
Has this been fixed? I still only see the pivot field on edit, not index/view pages.

**Comment by doctorallen** [comment]
I am also not seeing the field in the index page. I see the pivot value on the forms, but not on the index page.

**Comment by larsjanssen6** [comment]
@doctorallen you have to define the relation in both resources!

**Comment by Tarpsvo** [comment]
@larsjanssen6 Unbelievable, that did the trick for me! Thanks a ton.

**Comment by rickmacgillis** [comment]
In case someone else has this same issue, Issue #1714 is also a factor here. You'll need to make sure your `BelongsToMany` comes before your `BelongsTo` relationship. Presumably it's the same for `MorphToMany`.

**Comment by AlreadyIsTaken** [comment]
Hi for everyone!

I'm trying to implement data output from two models **Menus** and **Post** using many-to-many relationships and pivot table `**menu_post**`. The problem is that in the Nova resource, the belongsToMany field is not even displayed and there are no error notifications.

So there are 3 tables:
**posts** (it has fields: id, content)
**menus** (it has fields: id, title)
**menu_post** (it has fields: id, menu_id, post_id)

There are 2 models with the implementation of relationships

1. **/app/Menu.php**
`class Menu extends Model
{
    //
    public function contents(){
        return $this->belongsToMany('App\Post')->withPivot('post_id');
    }
}`

**2. /app/Post.php**
`class Post extends Model
{
    //
    public function menus(){
        return $this->belongsToMany('Aw\Menu')->withPivot('menu_id');
    }
}`

In the **Post resource**, I am trying to infer relative data from the **Menu model**.
**/app/Nova/Post.php**:

`class Content extends Resource
{
	public function fields(Request $request)
    {
        return [
            BelongsToMany::make('Menu'),
			Markdown::make('Content')
		];
	}
}`

But BelongsToMany field is not displayed in the resource,
how it fix?

**Comment by flexchar** [comment]
Hey,

quick notes:
1) your Post model has wrong namespace.

2) if I'm not mistaken, withPivot() means defining pivot model. You don't
have one. The second parameter in belongsToMany method takes the pivot
table name. Consult Laravel Docs for more details.

3) generate dump content and verify that all works in Laravel, then step
into Laravel Nova. One thing at a time ;)

**Comment by yevhenkoriakin** [comment]
How to hide this fields?

I have custom class MarketplaceProductFields
BelongsToMany::make('Marketplaces')->fields(new MarketplaceProductFields())

Hide not working. My field in invoke method:
            KeyValue::make('Settings')
                ->hideFromDetail()
                ->hideFromIndex()
                ->nullable(),
And i see it

![image](https://user-images.githubusercontent.com/8833710/72610198-7527a500-392f-11ea-87a8-e4a6ac859aec.png)

**Comment by lab08tonci** [comment]
I have same issues as @yevhenkoriakin 
Can we reopen this issue or, probably make another one?
By reading the comments seems like this is really messy functionality.

**Comment by sajanp** [comment]
Having same issue.  I'm the latest version as of today.

**Comment by socieboy** [comment]
I feel like Nova is missing a dedicated view for Pivot relations, the Detail view it’s not enough when you want to show all records for a pivot table.

Does anyone know a custom package for that?
I have been searching for one and I just start my own

**Comment by pleone** [comment]
@taylorotwell @davidhemphill is this really solved? 
as today with nova 3.4.0 i can't see pivot fields in index view.

**Comment by rikohz** [comment]
Having same  issue with  nova 3.5.0
Pivot field is shown in Add and Edit forms, but not in View and Index

**Comment by amidesfahani** [comment]
@taylorotwell @davidhemphill @larsjanssen6 

Still not working for me

nova: 3.6

```
BelongsToMany::make(__('Products'), 'products', Product::class)->fields(function () {
                return [
                    Number::make(__('Quantity'), 'quantity')->min(0)->step(1)->default(0)->required(),
                    Text::make(__('Price'), 'price')->displayUsing(function ($value) {
                        return ! is_null($value) ? number_format($value) : null;
                    })->sortable()->default(0),
                ];
            }),
```

Model:
```
public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot(['quantity', 'price'])->withTimestamps();
    }
```

is it possible to have different index fields for relations and fields for resource index?

**Comment by janpantel** [comment]
Not nice but gets the job done. Here is my solution:

Let's say you have `Order` and `Product` with a 'quantity` pivot field and want to show the quantity for each product in the order.

`app/Order.php`
```php
class Order extends Model {
    public function products()
    {
        $this->belongsToMany(Product::class)->withPivot('quantity');
    }
}
```

`app/Nova/Product.php`
```php
// ...
    public function fields()
    {
        return [
            //...
            Number::make('quantity')
                ->onlyOnIndex()
                ->showOnIndex(fn () => isset($this->pivot))
                ->displayUsing(fn () => isset($this->pivot) ? $this->pivot->quantity : null),
        ];
    }
//...
```

**Comment by henrypenny** [comment]
Thanks @janpantel that's a helpful trick.

**Comment by NanoCellWebDesign** [comment]
has this been solved yet?
I'm on latest version of nova as of posting this and I have managed to get it to display in edit using the code below but surely this shouldn't be necessary to get it to work and the code below still don't work for index pages:

`Text::make('Role', 'role')->displayUsing(function(){
       return isset($this->pivot) ? $this->pivot->role : '-';
}),`

**Comment by judahnator** [comment]
Same issue, using Nova 3.20.0

**Comment by crynobone** [comment]
Hi there, this issue has been marked as fixed and done based on above description, reproducing code and test done on our side. If you still have a problem please create a [New Issue](https://github.com/laravel/nova-issues/issues/new?assignees=&labels=&template=1_Bug_report.md) with full description on how to reproduce the issue based on your use case.
