### ISSUE TITLE
404 after create when primary key is not id

### ISSUE THREAD

**Issue by loren138** [laravel/nova-issues#189]
When creating a new resource, it tries to go to the view resource page by grabbing `.id` off the returned object.  However, if you primary key is not `id`, it gets `undefined` (so a url like `/resourceName/undefined`) and then goes to the 404 page.

I'm currently working around this by adding the below code to all my models to append an `id` attribute:
```
    protected $appends = ['id'];

    public function getIdAttribute() {
        if (array_key_exists($this->primaryKey, $this->attributes)) {
            return $this->attributes[$this->primaryKey];
        }
        return null;
    }
```

**Comment by bradders** [comment]
I ran into this issue too, although my issue was my model (User) had the `id` field hidden.

`protected $hidden = ["id"]`

Not a fix, as such, but I just removed the attribute from the hidden array.

**Comment by randelsr** [comment]
After poking around forever I finally stumbled on this. Thank you for the temporary workaround... hopefully this is resolved ASAP

**Comment by moleculezz** [comment]
I have a similar issue. But mine is because I'm using mongodb as the database for one specific model. mongodb uses `_id` as it's key.
When I inspect the request. The response indeed only has `_id`. So Nova is returning undefined because it doesn't find the `id` field.

**Comment by moleculezz** [comment]
Also, adding the `appends` attribute to the model doesn't work. But it does, if I add it in the `jenssegers/laravel-mongodb` model.

**Comment by webhealer** [comment]
@moleculezz  i am experiencing same problem with mongo db. Just i found a solution to make the id field hidden  with this way  ID::make('ID', 'id')->withMeta(['type' => 'hidden']),

also  i do not define _id as a primary key in model file  .  Hidden field also have problem with labels, field is now hidden but field label still visible. At least now it's working.

**Comment by paras-malhotra** [comment]
Created a PR in the Nova repo to fix this.

**Comment by loren138** [comment]
Given this is issue 189. I would say the other is a duplicate of this one.

**Comment by dkulyk** [comment]
I believe It will be fixed in closest releases.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by shankargiri** [comment]
@dkulyk  When can we expect the next release with the fix ?

Has anyone found any work-around so far ?

**Comment by dkulyk** [comment]
v1.3.1 already released.

**Comment by shankargiri** [comment]
@dkulyk - even after updates to v1.3.1, I am still having the same issue: 
This is what I have: 
1. Model has primary key as `user_id` and has been explicitly defined in Model and non-incremental. 
2. Tried defining field in resource class as (` ID::make('User ID', 'user_id'),` as well as (` Text::make('User ID', 'user_id'),`)
3. When I try to update the resource, resource keeps looking for `ID` during unique validation, says `unknown column "ID"`

Am I missing anything ?

**Comment by dkulyk** [comment]
This issue about another thing. You may create another issue.
