### ISSUE TITLE
Nova creating duplicate resources on Firefox

### ISSUE THREAD

**Issue by lasselehtinen** [laravel/nova-issues#2043]
- Laravel Version: 6.2.0
- Nova Version: 2.4.0
- PHP Version: 7.3.9
- Database Driver and Version: MySQL 5.7.27
- Operating System and Version: CentOS Linux release 7.7.1908
- Browser type and version: Firefox 69.0.3
- Reproduction Repository: 

### Description

We got this strange bug on some end users using Firefox. When creating a resource, it always creates duplicates. This works fine on Edge and Chrome. This only started appearing after we upgraded to Laravel 6 and Nova 2.4.

When there is an unique restraint:
![image](https://user-images.githubusercontent.com/1290186/66809587-5253b200-ef36-11e9-8f70-446aed0c95e8.png)

When no unique restraint, it will create a duplicate:
![image](https://user-images.githubusercontent.com/1290186/66809991-0f460e80-ef37-11e9-9f1b-c2c74db9d779.png)

### Steps To Reproduce

Start creating a new resource and click "Create ResourceName".

**Comment by lasselehtinen** [comment]
This might be a bug related to Firefox, Firefox 69.0.3 was released October 10, 2019 and this is after the users started to experience this issue. On 69.0.2 it was reported to be working fine.

**Comment by podcasthosting** [comment]
Same here with:

Laravel Version: 5.8.0
Nova Version: 2.4.0
PHP Version: 7.2.23
Operating System and Version: openSUSE Tumbleweed
Browser type and version: Firefox 69.0.2

**Comment by h-zone** [comment]
Confirm:
* macBook Air 13 / 2014 + Firefox
* Windows 10 Pro + Firefox

**Comment by jbrooksuk** [comment]
Investigating this now, but if @lasselehtinen is right and it is a Firefox issue, there isn't anything we can do other than let Firefox know.

**Firefox works in 68.0.2 (64-bit)**

![image](https://user-images.githubusercontent.com/246103/66816401-ecfdc200-ef31-11e9-91a3-471e85a3fb10.png)

I'm updating now and will see if it's still broken.

**Comment by jbrooksuk** [comment]
I'm now on Firefox 69.0.3 (64-bit) and I do get this when submitting a form:

![image](https://user-images.githubusercontent.com/246103/66817868-51218580-ef34-11e9-87ec-5222d74efca9.png)
![image](https://user-images.githubusercontent.com/246103/66818028-980f7b00-ef34-11e9-8995-00100542a6ad.png)

But it does look like this is already fixed on the `2.4` branch which should see a release later today.

**Comment by mattyh88** [comment]
This issue is still the case for: 

Laravel version 6.3.0 
Nova version: 2.4.0
PHP version: 7.3.8
Browser: Firefox 70.0
OS: MacOS Mojave 10.14.5

**Comment by jbrooksuk** [comment]
Upgrade to Nova 2.5.0

**Comment by mattyh88** [comment]
Sorry I copy pasted the Laravel Nova version from the original author of this issue and did not update the version in my post. I'm already on Nova 2.5

**Comment by jbrooksuk** [comment]
Re-publish your assets.
