### ISSUE TITLE
problem with generating new nova tools

### ISSUE THREAD

**Issue by squierll** [laravel/nova-issues#245]
Environment: Win 10 (Using laravel homestead)

I have a problem when I want to create a new nova tool. 
If create tool without dependencies (npm and composer), does not display a new tool. 
There is a link with the new tool in the menu, but does not show me the Tool.vue component.

**Comment by julianpoma** [comment]
Are you having this issue too? #143

**Comment by squierll** [comment]
I found a solution and now everything works perfectly.
The problem was in webpack.mix.js

Default webpack tool file:

```
let mix = require('laravel-mix')

mix.js('resources/js/tool.js', 'dist/js')
   .sass('resources/sass/tool.scss', 'dist/css')
```
I just added `_dirname +`
```
let mix = require('laravel-mix')

mix.js('resources/js/tool.js', __dirname + 'dist/js')
   .sass('resources/sass/tool.scss', __dirname + 'dist/css')

```

**Comment by davidhemphill** [comment]
Just pushed a fix for Windows when compiling assets. 🚀 This has been fixed and will be included in an upcoming release.

**Comment by ghaskell** [comment]
Thanks for this.

**Comment by jameslieu-twentyci** [comment]
I'm having the same problem, just updated to `1.1.7` and still running into the same problem. Please let us know which release it'll be. Thanks

**Comment by shenryuken** [comment]
i'am having this issue again..Before this 1.0.17 solved this problem with fresh installation. Windows 10 Environment.. But now even 1.0.17 to the latest this issue not solved
