### ISSUE TITLE
File field does not shown on the creating form

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#2521]
- Laravel Version: 7.5.0
- Nova Version: 3.4.0
- PHP Version: 7.4.4
- Database Driver & Version:
- Operating System and Version: Linux
- Browser type and version: Chrome 81

### Description:
In the creation form, File(Image) field is not displayed if the file cannot be deletable.
Maybe was broken in https://github.com/laravel/nova/commit/1f7ab0012393be828de22e3bc970f04f13746f32
![image](https://user-images.githubusercontent.com/370042/79469719-34f8c100-8009-11ea-9964-2bdd1d10a6e2.png)

### Steps To Reproduce:
Add File field with deletable(false)
```php
Image::make('Image')
    ->deletable(false)
```

**Comment by v-bubar** [comment]
Was this issue addressed somehow? The problem still persists on the version i use (3.3.2).

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by jbrooksuk** [comment]
https://nova.laravel.com/releases/3.4.1

**Comment by v-bubar** [comment]
Thanks!

**Comment by SquareBeard** [comment]
Still not working for me with 3.4.1
Am I missing something ?

**Comment by pawelmysior** [comment]
> Still not working for me with 3.4.1
> Am I missing something ?

Same for me @SquareBeard.

My env: Laravel version 7.7.1, Nova version 3.4.1, PHP version 7.4.4.

**Comment by chescos** [comment]
This issue is still not fixed @jbrooksuk - occurs on Nova 3.4.1.

**Comment by mrmonat** [comment]
The issue is, that the js was not bundled for version 3.4.1

To fix this:

```
cd /vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install && npm run production
```

now in the root of the laravel installation:

`php artisan nova:publish`

**Comment by SquareBeard** [comment]
Confirmed fixed in 3.5.0

**Comment by pawelmysior** [comment]
Thank you Nova team for fixing this! 🤟
