### ISSUE TITLE
Can't update resource with image in Firefox

### ISSUE THREAD

**Issue by SlavaRazum** [laravel/nova-issues#273]
When resource has image field and you try to update resource by **Update** or **Update & Continue**, JavaScript throws error
> Unhandled promise rejection TypeError: "e.t0.response is undefined"

![Screenshot](https://image.prntscr.com/image/lEOaXINrTByZOUo7ZGx-WQ.png)

But when you choose a file it works fine.

MacOS High Sierra 10.13.6
Firefox 61.0.2

**Comment by jernejcvek** [comment]
I have the same issue (also reported in #135) on **Firefox** 61.0.2 @ Ubuntu 16.04 LTS.

However, in Chrome (68.0.3440.106) updating resource without Image **does not** cause problems.

**Comment by bradykeeling** [comment]
I'm having the same issue in the latest version of FIrefox.

I also receive an error in Chrome when I try to update a resource that already has an image attached.  It tells me that the field is required.

This happens when the field is _not_ set to nullable in the migration.

![screen shot 2018-08-28 at 11 46 20 am](https://user-images.githubusercontent.com/3791996/44737577-0470b600-aab8-11e8-96c5-eedb21c2b491.png)

**Comment by bradykeeling** [comment]
Thanks for the response @jernejcvek.  

For this example the image is already attached to the model, but when I try to update it, it says that the image field is required (even though the location is obviously being stored in the database field, because it's showing a thumbnail of the image). 

Does that make sense?  Am I just missing something obvious?

**Comment by bradykeeling** [comment]
It appears that my problem is a bit different than the initial post, so I moved it to #353

**Comment by HUN-Julian** [comment]
Hi Folks,

I have exactly the same issue with simple file field on update event.  Is there any solution?
Nova v1.0.8 | FF 60.0.2 (64-bit)

**Comment by v1nk0** [comment]
I can confirm that **updating** a resource with an image-field is not possible with Firefox if you are not sending a new image each time. 
Tested with Nova 1.0.12 and FF 61.0.2 Windows as well as FF 61.0.2 macOS.

<img width="809" alt="screen shot 2018-09-07 at 12 47 08" src="https://user-images.githubusercontent.com/8701964/45214987-41009680-b29c-11e8-8116-316de9fa1066.png">

This is **without** having a "required" rule for the image field.
It only works when I send a new file with the update request. 

With Edge I'm experiencing a server-error on exactly the same action (updating with a image already present and not sending a new image):
<img width="1264" alt="screen shot 2018-09-07 at 12 50 44" src="https://user-images.githubusercontent.com/8701964/45215110-b0768600-b29c-11e8-9c19-6c21caa4994c.png">

The **exact same action** works perfectly fine with Chrome though.

**Comment by Navi2016** [comment]
Creating a new post without sending an image does not seem to work in firefox either. Field is nullable and not required, still getting the above js error.

When selecting an image and then trying to save makes the validation for the rest of the form work.

**Comment by DonDiegoAA** [comment]
This bug is still there with Nova 1.1.3

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by duykpro** [comment]
Same issue here, cant update on Firefox

**Comment by sheldonkotyk** [comment]
Also an issue in Safari.

**Comment by v1nk0** [comment]
@duykpro @sheldonkotyk The latest release (v1.1.4) is from October 1st and @davidhemphill wrote on October 2nd that a fix will be included in an upcoming release, so I guess there's nothing but to wait for a Nova release with the fix. 

@davidhemphill can you confirm that a fix is included in the **next** release, because you've wrote **an upcoming** release, which doesn't necessarily means the next ;)? Any ETA on the next release?

**Comment by jwahdatehagh** [comment]
I'm on 1.1.4 as well and can confirm this is not fixed yet.

**Comment by XGhozt** [comment]
I'm assuming this will be fixed soon, we haven't had a release in nearly 4 weeks now.

**Comment by UdyW** [comment]
This is a major issue!!! Its now happening in chrome as well. 

Reproduce steps;
1. Save image with the record
2. Select the record to edit
3. Try updating the record changing something other than the image field.

<img width="1333" alt="screenshot 2018-10-24 at 09 44 09" src="https://user-images.githubusercontent.com/6145036/47418147-72142800-d771-11e8-8efa-fe2de7a9f144.png">
`    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Text::make('Title')
                ->sortable()
                ->rules('required', 'max:255'),

            Text::make('Header title')
                ->sortable()
                ->rules('required', 'max:254'),

            Text::make('Header caption')
                ->rules('required', 'string', 'min:6'),

            Image::make('Banner Image')
                ->rules('required'),

            Textarea::make('Content')
                ->rules('string', 'min:6'),

            Text::make('Slug')
                ->resolveUsing(function($slug){
                    return str_slug($slug);
                }),
        ];
    }`
Hope this will be fixed soon.

**Comment by flexchar** [comment]
Briefly confirming bug, updating resource does nothing when on Firefox, Edge. Chrome works fine.

**Comment by Navi2016** [comment]
The Nova releases seem to have stopped, feel kind of ripped off.

**Comment by tiagosimoesdev** [comment]
we all got in the hype train  . Bought nova , really tried for two weeks to build a custom admin panel , but the amount of work / effort is just not really worth . 

I think nova it's an "extra" for an admin panel if it's simple enough.  Back to backpack ..

**Comment by tiagosimoesdev** [comment]
@jmonday-ci  not the best place to promote it ( I'm not in any way affiliated with backpack ) , but it's really great that the community can help it develop .

**Comment by lvdhoorn** [comment]
Personally i think Nova is a great tool to work with. The problem with downloading an image or updating a resource that already contains an image does not work in Nova 1.1.8. For now we just use Chrome but it would be nice if the bug gets fixed.

**Comment by rovansteen** [comment]
I think it's better to create a new issue if a bug is not fixed (properly) rather than keep commenting on closed issues. I doubt they will check comments on closed issues.

**Comment by slavarazum** [comment]
Have no this issue on 1.1.8 version. Did you republish nova assets?
```bash
php artisan vendor:publish --tag=nova-assets --force
```

**Comment by lvdhoorn** [comment]
@slavarazum did you try to edit a resource that already has an image in FireFox? Because that is the problem. In Chrome it is working fine. Running php artisan vendor:publish --tag=nova-assets --force did not solve the problem :(

**Comment by slavarazum** [comment]
@lvdhoorn Yes, for example if user already have an avatar, I can change it.
My Firefox Version:
![My Firefox Version](https://image.prntscr.com/image/nqO32Y3dQSGFfYYCXh6m6g.png)
Also try to:
```
php artisan view:clear
```
And refresh FireFox cache.

**Comment by lvdhoorn** [comment]
@slavarazum weird i have the same version FireFox, I run php artisan view:clear and my cache is cleared. In the console is see the following error when i hit the update button Unhandled promise rejection TypeError: "e.t0.response is undefined"

**Comment by slavarazum** [comment]
@lvdhoorn Sounds strange. Are you on 1.1.8 version?
Maybe try it on fresh Laravel installation.

**Comment by XGhozt** [comment]
@lvdhoorn I have an issue every time I update Nova. For some reason, I have to manually delete the `public/vendor/nova` folder and run `php artisan nova:publish` in some cases, with the `--force` option, too. It's possible you updated Nova but the javascript files are still the old version. Check the modified date on those files to make sure they're the new ones.

**Comment by davidhemphill** [comment]
You have to update Nova's published assets every time you upgrade to a new version or you won't get the new versions of them. 👍 `php artisan nova:publish`

**Comment by davidhemphill** [comment]
What's the consensus here? I've revisited this issue and from my tests can't reproduce the problem. Is it fixed or not? From what I can tell, it is.

**Comment by lvdhoorn** [comment]
The problem still exist in our application in Firefox 63.0.3 and Nova 1.2.0.

I have tried `php artisan nova:publish --force` without luck.

We run Nova with Composer and the app url is just /

In Google Chrome and Safari it is working fine.

In FireFox when i want to update the resource i see the picture but i can't save the resource until i select the picture again from the computer by clicking browse. If i not select the picture i get the following error in the console;

> Unhandled promise rejection TypeError: "e.t0.response is undefined"

When viewing the detail page from a resource i see the picture but i can't download it.
When i click on download there are no errors in the console.

In Safari downloading is working but updating not (version 12.0.1).

In Google Chrome both is working (version 70.0.3538.110)

**Comment by XGhozt** [comment]
@lvdhoorn -- did you try my solution? Short list:

1. Delete your `/vendor` folder
2. Delete your `/public/vendor/nova` folder
3. Confirm `/nova` is up to date (best way might be to delete the nova folder and add a fresh copy)
4. Run `composer install` (re-add vendor folder)
5. Run `php artisan nova:publish` (re-add public vendor folder)
6. Clear your browser cache

**Comment by lvdhoorn** [comment]
Oké the problem is solved. We have a couple off custom views and they where pointing to the old asset folder. The old asset folder was still on the server so there where no errors.

**Comment by jBOKA** [comment]
Still not working in my case v1.2.1

**Comment by dsampaolo** [comment]
I finally managed to solve this by republishing Nova assets, as stated by @davidhemphill.
Problem solved on Firefox Nightly.

My assets were in /public/nova-assets, they now are in /public/vendor/nova. Hope this helps.

**Comment by mrigo** [comment]
Hello,
the issue for me is still present with Nova 1.3.2.
I've tried republishing Nova but with no luck.
I'm using S3 as a disk, could be this the cause?

```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Name', 'name')->sortable()->rules('required'),
            Number::make('Latitude', 'lat')->step(0.00000001)->rules('required'),
            Number::make('Longitude', 'lng')->step(0.00000001)->rules('required'),
            Number::make('Range (mt)', 'range')->onlyOnForms(),
            Number::make('Range', function() {
                return $this->range." mt";
            }),
            File::make('Audio file', 'audio')
                ->disk('s3')
                ->path('audio_files')
                ->storeSize('attachment_size')
                ->rules('required','mimetypes:audio/mpeg,audio/x-aac,audio/x-aiff')
                ->storeAs(function(Request $request){
                    return $request->audio->getClientOriginalName();
                }),
        ];
    }
```
Here the error message when I try to update the resource even if the file is already present:

![Schermata 2019-05-10 alle 16 08 28](https://user-images.githubusercontent.com/2822656/57533371-e5f8d500-733d-11e9-8b4f-643be1b053d6.png)


Thanks
\m

**Comment by mrigo** [comment]
Hello, anyone?

**Comment by Navi2016** [comment]
The issue is closed (and seems fixed for me), if you still have problems and want a response, please open a new ticket or re-open this one.

**Comment by mrigo** [comment]
I've digged about, found
->creationRules
->updateRules
still not so intuitive solution but working, thanks!

**Comment by paperscissors** [comment]
A bit confused why this is still a thing on 3.0/dev-master. Hadn't seen this before but for some reason it's happening to me now --- and I don't even have an image field on this resource.

**Comment by crynobone** [comment]
@paperscissors This is a 2 year old issue, if you have a new issue related to this please create a new issue with full details and reproducing steps.
