### ISSUE TITLE
Help texts have disappeared from attach view

### ISSUE THREAD

**Issue by devfrey** [laravel/nova-issues#2878]
- Laravel Version: 8.4.0
- Nova Version: 3.10.0 (bug introduced in 3.9.0)
- PHP Version: N/A
- Database Driver & Version: N/A
- Operating System and Version: N/A
- Browser type and version: N/A
- Reproduction Repository: none

### Description:
Help texts have disappeared from the attach view. I wasn't sure if this was intentional or not, so I dug into the source code and Git history. Here's what I found:

The visibility of the help text is determined by the `showHelpText` prop. The default for this prop [used to be `true`](https://github.com/laravel/nova/commit/7fee1bc3eda064f1998ff0aa515d995c7513801b#diff-6958570efb5406cd982ddc49f6fd77c1L43), but [was changed to `false`](https://github.com/laravel/nova-js/commit/d7bcaac65da5355c3f22821db2821ca979759dd7#diff-7a15f168d27541b7286b7a61181e3b10R6).

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add a resource with a `BelongsToMany` field with help text. The help text will not be shown on the attach screen.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by devfrey** [comment]
@davidhemphill Any chance this fix could be released soon?

**Comment by davidhemphill** [comment]
We usually release new versions every other Tuesday. The next release is tomorrow!

**Comment by devfrey** [comment]
The issue is still partially present. I've opened a PR to fix the remaining issue: https://github.com/laravel/nova/pull/1007
