### ISSUE TITLE
Save Images: Unhandled Promise Rejection: TypeError

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#378]
After that I've created an Object with an Image, I'm not able to update the Model without selecting a new Image. Evena Image is already attached to the Model.

`Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.t0.response.status')`

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/10268813/44927152-c8598180-ad53-11e8-8517-697ff5740252.png">

```
   Image::make('Member Photo')
                ->sortable()
                ->rules('required','image')
                ->disk('public'),
```

**Safari**: Version 11.1.2 (13605.3.8)

**Comment by v1nk0** [comment]
The problem is that if you add the rule "required", you always need to send an image (same for file and avatar field-type) The fact that an image (or file / avatar) is already present does not affect the "required"-rule.
See #353 

In **Firefox and Chrome** (macOS) this is at least clear as normal validation errors are shown.
In **Safari** (macOS) though, no validation errors are shown. Instead, the console shows a js-error:

<img width="915" alt="screen shot 2018-09-04 at 15 08 44" src="https://user-images.githubusercontent.com/8701964/45033308-731fb780-b054-11e8-8098-8b8907772f71.png">

It seems to be the same error as @StanBarrows gets.

_Clicking on that errors shows following error-position:_

<img width="452" alt="screen shot 2018-09-04 at 15 09 12" src="https://user-images.githubusercontent.com/8701964/45033330-80d53d00-b054-11e8-923e-b7ef64a91673.png">

_And stack trace:_

<img width="918" alt="screen shot 2018-09-04 at 15 11 57" src="https://user-images.githubusercontent.com/8701964/45033469-e88b8800-b054-11e8-8a3b-f3e557426505.png">

**Comment by krisons** [comment]
Same problem. Safari on Mac

**Comment by sijones-uk** [comment]
Also seeing this problem, Firefox 61.0.2 on a PC. Chrome on a PC is fine. I wasn't able to find a workaround, which is a bit of a problem if you want to use an Image/Avatar field.

**Comment by weeman1337** [comment]
Same with Firefox 62.0

**Comment by AegirLeet** [comment]
The real error is 
> TypeError: "Argument 2 of FormData.append is not an object."

Triggered in FileField.vue (the `formData.append(...)` bit).

**Comment by v1nk0** [comment]
@AegirLeet did you manage to make a workaround?

This problem is making it impossible to use Firefox or Edge (I even believe it only works without problems if you use Chrome) as soon as a File field (this includes Image and Avatar) is on a resource and a **new file** is not necessarily needed each time you update a record of this resource.

_Problem still occurs with the latest Nova (v1.0.15)_

**Comment by AegirLeet** [comment]
@v1nk0 In FileField.vue, look for the `formData.append(...)` and replace it with 
```
if (this.file) {
    formData.append(...)
}
```

Seems to be working so far.

**Comment by v1nk0** [comment]
@AegirLeet maybe stupid question, but how do I recompile the .js-file of Nova after I made that change in the .vue-file (nova/resources/js/components/Form/FileField.vue) ?
I could not locate a build-script for Nova....

**Comment by AegirLeet** [comment]
@v1nk0 Copy the webpack.mix.js.dist to webpack.mix.js and run `npm run prod` - just like a regular Laravel application.
Then just copy everything from _public/_ to your application's _public/nova-assets/_.

**Comment by v1nk0** [comment]
> @v1nk0 Copy the webpack.mix.js.dist to webpack.mix.js and run `npm run prod` - just like a regular Laravel application.
> Then just copy everything from _public/_ to your application's _public/nova-assets/_.

Yes, did that first step.
I think it's too late already, I just forgot to install dependencies first 🤫. Works now.... of course....

**Comment by laurencei** [comment]
I've got this same issue. v1.0.16

**Comment by DonDiegoAA** [comment]
I'm probably miss something here, but why don't you use creationRules and updateRules ?

```
Avatar::make('Image')->disk('public')
                ->creationRules('required', 'image','mimes:jpg,jpeg,png,gif')
                ->updateRules('nullable', 'image','mimes:jpg,jpeg,png,gif'),
```

**Comment by v1nk0** [comment]
@DonDiegoAA this issue has nothing to do with the required-rule.
Even if you don't set the field to be required, the error occurs (at least with when not using Chrome)

**Comment by DonDiegoAA** [comment]
Ok, I see that on Firefox too now, sorry I should have read better.

**Comment by cdupoiron** [comment]
same issue on 1.1 and 1.1.1 on FF

**Comment by laurencei** [comment]
Yeah - I checked as well.

Latest Nova versions 1.1.1 on Firefox - promises error
Same website/page on Chrome - no issue

**Comment by webhealer** [comment]
Same issue here: (nova version 1.0.19)

Avatar field with following details:

`            Avatar::make('Avatar')->disk('public')
                    ->path('avatar')
                    ->prunable()
                    ->hideWhenCreating()
                    ->rules('nullable'),`

is giving the following error on FF:  ( Firefox version 62.0 (64-bit) for Ubuntu)

`Unhandled promise rejection TypeError: "_context2.t0.response is undefined"
_callee2
http://laravel.local/vendor/nova/vendor.js?id=a17854ec0fcced7c87f7:95225:15 app.js:28755:11
onUnhandled`

It's working good on Chrome.

**Comment by eblount** [comment]
Confirm that the issue still exists in 1.1.3 on Firefox

**Comment by vootrunner** [comment]
The issue still exists in 1.1.3 on Safari too

**Comment by antoniolore** [comment]
The issue still exists in 1.1.4 on Safari and Firefox

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release. Sorry it took so long!

**Comment by laurencei** [comment]
@davidhemphill - any chance the next release can be tagged with this fix?

**Comment by nickpoulos** [comment]
Is this fix available to use yet? I believe I am using the latest Nova release but I am still seeing this bug.

**Comment by laurencei** [comment]
@nickpoulos - no unfortunately. 

It'll be in the "next" release of Nova (ETA unknown)

**Comment by alberto-bottarini** [comment]
Any news?
I'm still having this error: `Unhandled promise rejection TypeError: "e.t0.response is undefined; can't access its "status" property"`

**Comment by jBOKA** [comment]
Still not working for me in v1.2.1, same as https://github.com/laravel/nova-issues/issues/378#issuecomment-435781437

**Comment by ceejayoz** [comment]
@jBOKA Thanks, this was our issue as well.

**Comment by S-anasol** [comment]
Regression probably

v1.3.2

again same error

![image](https://user-images.githubusercontent.com/1709666/53978104-7a1aa600-411b-11e9-8abe-4c493ea7d59d.png)
