### ISSUE TITLE
Resource-tool npm run dev opens notepad

### ISSUE THREAD

**Issue by bakkertjebrood** [laravel/nova-issues#3844]
- Laravel Version: 9.7.0
- Nova Version: 4.0.0
- PHP Version: 8.0
- Database Driver & Version: Mysql
- Operating System and Version: Windows 11 Home
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
When running npm run watch or npm run dev on new resource-tool, npm opens notepad and does not create a dist folder

### Detailed steps to reproduce the issue on a fresh Nova installation:
New Laravel and new Nova 4.0 repo. Create an (barebone) resource-tool with php artisan nova:resource-tool <name>. Try to run npm watch or npm run dev

![image](https://user-images.githubusercontent.com/11925329/161979536-d5939190-aa33-4a3f-ac6e-6fff35ccabd6.png)

**Comment by Paulsky** [comment]
I also encountered this problem. I think it has to do with the import "import Tool from './components/Tool'" in tool.js. There is no 'Tool.vue' or 'Tool.js' file generated in the /components directory.

**Comment by crynobone** [comment]
> I also encountered this problem with 'nova:tool'. I think it has to do with the import "import Tool from './components/Tool'" in tool.js. There is no 'Tool.vue' or 'Tool.js' file generated in the /components directory.

This has been fixed in `4.0.3` release.

![image](https://user-images.githubusercontent.com/172966/161999078-b4901a1b-b64d-4a8c-a99e-008f687a6468.png)

**Comment by crynobone** [comment]
Can you test renaming `mix.js` to `nova-mix.js` and update `webpack.mix.js` to `require('nova-mix')` if that solved the issue.

**Comment by bakkertjebrood** [comment]
> Can you test renaming `mix.js` to `nova-mix.js` and update `webpack.mix.js` to `require('nova-mix')` if that solved the issue.

That indeed solved the problem. Thx!

**Comment by classicalguss** [comment]
> Can you test renaming `mix.js` to `nova-mix.js` and update `webpack.mix.js` to `require('nova-mix')` if that solved the issue.

Hello, sorry but where do we change those? What are the paths of those files?
This issue still comes up.
