### ISSUE TITLE
Error not removed if click "Update & Continue Editing"

### ISSUE THREAD

**Issue by yaroslawww** [laravel/nova-issues#748]
1. make field required

`
  Textarea::make('Description')
                ->rules('required', 'max:20000')
                ->hideFromIndex(),
`
2. On edit resource (like: host.loc/admin/resources/events/2/edit) set field empty and click *Update & Continue Editing* => red error appear "The description field is required."
3. Set some text in field and click *Update & Continue Editing* => resource will updated BUT ERROR still visible
![screenshot](https://user-images.githubusercontent.com/23663794/46261312-91b18b00-c4fa-11e8-8add-7dde4d5affa2.png)

**Comment by bonzai** [comment]
This should be fixed in v1.0.18:

> Fix bug that caused validation errors to still show on update screen after update and continue editing.

#512

**Comment by yaroslawww** [comment]
I use latest version
`
/**
     * Get the current Nova version.
     *
     * @return string
     */
    public static function version()
    {
        return '1.1.3';
    }
`

And all assets are published after updating 
`
 php artisan nova:publish
`

But I still have this error https://prnt.sc/l0kjj7
